name: Preview on PR

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          
      - run: yarn
      - run: yarn build
      
      - name: Preview to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.STAGING_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=.next
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
